# Generated by Django 4.1.7 on 2023-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_handle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='Status',
            field=models.IntegerField(default='000'),
        ),
        migrations.DeleteModel(
            name='NoteSheetAdditional',
        ),
    ]
